name: heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: akhileshns/heroku-deploy@master # This is the action
        with:
          heroku_api_key: ${{ef4e4382-e1ed-42e0-9b6e-8dd96dc34e7c}}
          heroku_app_name: "ncsub01" #Must be unique in Heroku
          heroku_email: ${{mail@nchyn.net}}
          usedocker: true
